name: CML Sanity Test Data Poisoning

on:
  push:
    branches: test
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  train-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run poisoning analysis
        run: |
          python poisoning-data.py > result.txt
          cat result.txt

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Publish CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Data Poisoning Evaluation Report" > report.md
          cat result.txt >> report.md
          cml comment create report.md

